name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.19"

      - name: Install dependencies
        run: |
          go mod tidy
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.49.0

      - name: Run build
        run: go build .

      - name: Run vet
        run: |
          go vet .

      - name: Run lint
        run: |
          golangci-lint run .
